### ISSUE TITLE
Add Python Version Algorithms

### ISSUE THREAD

**Issue by Ogutu-Brian** [meshnesh/codilityAlgorithims#1]
# Given an integer array nums, find the contiguous subarray (containing at least one number) which has the largest sum and return its sum.
# Input: [-2,1,-3,4,-1,2,1,-5,4],
# Output: 6
# Explanation: [4,-1,2,1] has the largest sum = 6.

```
def max_sub_array(nums):
    if len(nums) == 1:
        return nums[0]

    total = nums[0]
    best = nums[0]

    for i in nums[1:]:
        if i > (total + i):
            total = i
        else:
            total += i

        best = max(best, total)

    return best
```
# Test
```
import unittest
from PythonVersion.Solutions.Algorithms import max_sub_array


class TestMaximumSubArray(unittest.TestCase):
    def test_example_array(self):
        self.assertEqual(6, max_sub_array([-2, 1, -3, 4, -1, 2, 1, -5, 4]))

```

**Comment by Ogutu-Brian** [comment]
Hello @meshnesh , could you add me as a contributor to this repository. I could do the python version for the algorithms

**Comment by maahi07m** [comment]
Max sum program @meshnesh :

arr=input().split()
arr=[int(i) for i in arr]
max_in_arr=-1000;s=0
for i in range(len(arr)):
    s=0
    for j in range(i,n):
        s=s+arr[j]
        if max_in_arr<s:
            max_in_arr=s
print(max_in_arr,end='')

**Comment by Ogutu-Brian** [comment]
The final result needs to be an integer, so I think you need a function that processes a list and returns the best as shown above

**Comment by Ogutu-Brian** [comment]
<img width="1439" alt="Screenshot 2020-03-13 at 09 20 18" src="https://user-images.githubusercontent.com/30015297/76595157-079d8c80-650c-11ea-9e3d-469436626bea.png">
Leet Code
